create extension if not exists pgcrypto;

create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 username text unique not null,
 full_name text not null default '',
 bio text not null default '',
 avatar_url text,
 is_creator boolean not null default false,
 is_business boolean not null default false,
 created_at timestamptz not null default now()
);

create table if not exists public.posts(
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 content text not null default '',
 image_url text,
 video_url text,
 created_at timestamptz not null default now()
);

create table if not exists public.post_likes(
 post_id bigint references public.posts(id) on delete cascade,
 user_id uuid references auth.users(id) on delete cascade,
 created_at timestamptz not null default now(),
 primary key(post_id,user_id)
);

create table if not exists public.comments(
 id bigint generated by default as identity primary key,
 post_id bigint references public.posts(id) on delete cascade,
 user_id uuid references auth.users(id) on delete cascade,
 content text not null,
 created_at timestamptz not null default now()
);

create table if not exists public.follows(
 follower_id uuid references auth.users(id) on delete cascade,
 following_id uuid references auth.users(id) on delete cascade,
 created_at timestamptz not null default now(),
 primary key(follower_id,following_id),
 check(follower_id<>following_id)
);

create table if not exists public.communities(
 id uuid primary key default gen_random_uuid(),
 name text unique not null,
 description text not null default '',
 owner_id uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now()
);

create table if not exists public.community_members(
 community_id uuid references public.communities(id) on delete cascade,
 user_id uuid references auth.users(id) on delete cascade,
 role text not null default 'member',
 created_at timestamptz not null default now(),
 primary key(community_id,user_id)
);

create table if not exists public.conversations(
 id uuid primary key default gen_random_uuid(),
 created_at timestamptz not null default now()
);

create table if not exists public.conversation_members(
 conversation_id uuid references public.conversations(id) on delete cascade,
 user_id uuid references auth.users(id) on delete cascade,
 created_at timestamptz not null default now(),
 primary key(conversation_id,user_id)
);

create table if not exists public.messages(
 id bigint generated by default as identity primary key,
 conversation_id uuid references public.conversations(id) on delete cascade,
 sender_id uuid references auth.users(id) on delete cascade,
 body text not null,
 created_at timestamptz not null default now()
);

create table if not exists public.notifications(
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade,
 actor_id uuid references auth.users(id) on delete set null,
 type text not null,
 entity_id text,
 read_at timestamptz,
 created_at timestamptz not null default now()
);

create table if not exists public.reports(
 id bigint generated by default as identity primary key,
 reporter_id uuid references auth.users(id) on delete cascade,
 target_type text not null,
 target_id text not null,
 reason text not null,
 status text not null default 'open',
 created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.comments enable row level security;
alter table public.follows enable row level security;
alter table public.communities enable row level security;
alter table public.community_members enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.reports enable row level security;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select using (true);
drop policy if exists profiles_self_write on public.profiles;
create policy profiles_self_write on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);

drop policy if exists posts_read on public.posts;
create policy posts_read on public.posts for select using (true);
drop policy if exists posts_insert on public.posts;
create policy posts_insert on public.posts for insert with check (auth.uid()=user_id);
drop policy if exists posts_update on public.posts;
create policy posts_update on public.posts for update using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists posts_delete on public.posts;
create policy posts_delete on public.posts for delete using (auth.uid()=user_id);

drop policy if exists likes_read on public.post_likes;
create policy likes_read on public.post_likes for select using (true);
drop policy if exists likes_write on public.post_likes;
create policy likes_write on public.post_likes for all using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists comments_read on public.comments;
create policy comments_read on public.comments for select using (true);
drop policy if exists comments_write on public.comments;
create policy comments_write on public.comments for all using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists follows_read on public.follows;
create policy follows_read on public.follows for select using (true);
drop policy if exists follows_write on public.follows;
create policy follows_write on public.follows for all using (auth.uid()=follower_id) with check (auth.uid()=follower_id);

drop policy if exists reports_insert on public.reports;
create policy reports_insert on public.reports for insert with check (auth.uid()=reporter_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id, username, full_name)
  values(
    new.id,
    coalesce(nullif(split_part(new.email,'@',1),''), 'user_' || substr(new.id::text,1,8)),
    coalesce(new.raw_user_meta_data->>'full_name','')
  )
  on conflict(id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();
